name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # React Project Build
      - name: Install Dependencies for React App
        run: |
          cd AI_Fluency_Replit
          npm install

      - name: Build React App
        run: |
          cd AI_Fluency_Replit
          npm run build

      # Prepare Static Files
      - name: Prepare Static Files
        run: |
          mkdir -p dist
          cp -r AI_Fluency_Replit/dist/* dist/
          mkdir -p dist/flowith
          cp -r AI_Fluency_Flowith/* dist/flowith/

      # Deploy to GitHub Pages - for project repository
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          clean: true