name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'AI_Fluency_Replit/package-lock.json'

      # React Project Build with caching
      - name: Install Dependencies for React App
        run: |
          cd AI_Fluency_Replit
          npm ci

      - name: Build React App
        run: |
          cd AI_Fluency_Replit
          npm run build

      # Prepare Static Files
      - name: Prepare Static Files
        run: |
          # Create dist directory
          mkdir -p dist
          
          # Copy React app files
          cp -r AI_Fluency_Replit/dist/* dist/
          
          # Create flowith directory and copy files
          mkdir -p dist/flowith
          cp -r AI_Fluency_Flowith/* dist/flowith/
          
          # Create landing page in dist directory
          cp index.html dist/
          
          # Create .nojekyll file to disable Jekyll processing
          touch dist/.nojekyll
          
          # Debug: List contents of dist directory
          echo "Contents of dist directory:"
          ls -la dist/
          echo "Contents of dist/flowith directory:"
          ls -la dist/flowith/
          
          # Create a README file to explain the repository
          echo "# AI Fluency Guide\n\nThis repository contains the AI Fluency Guide in two versions:\n\n- React version\n- HTML/CSS/JS version (in /flowith directory)" > dist/README.md

      # Deploy to GitHub Pages - for project repository
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          clean: true